Task1_django/djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path
from web import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('stu', views.stu),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),

]

Task1_django/djangoproject/web/models.py
from django.db import models

class Students(models.Model):
    sid = models.CharField(max_length=30)
    name = models.CharField(max_length=50)
    father = models.CharField(max_length=50)
    mother = models.CharField(max_length=50)
    email = models.EmailField()
    degree = models.CharField(max_length=40)
    gender = models.CharField(max_length=10)

    class Meta:
        db_table = "students"

Task1_django/djangoproject/web/forms.py
from django import forms
from web.models import Students




class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = "__all__"

Task1_django/djangoproject/web/views.py
from django.shortcuts import render, redirect
from web.forms import StudentsForm
from web.models import Students



def stu(request):
    if request.method == "POST":
        form = StudentsForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form = StudentsForm()
    return render(request, "index.html", {'form':form})


def show(request):
    studentvar = Students.objects.all()
    return render(request,"show.html",{'studentvar': studentvar})

def edit(request, id):
    students = Students.objects.get(id=id)
    return render(request,"edit.html",{'students': students})

def update(request, id):
    students = Students.objects.get(id=id)
    form = StudentsForm(request.POST, instance = students)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request,"edit.html",{'students': students})
    


def delete(request, id):
    students = Students.objects.get(id=id)
    students.delete()
    return redirect('/show')

Task1_django/djangoproject/web/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{students.id}}">
    {% csrf_token %}
    <class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
    </div>
    
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Students ID: </label>
    <div class="col-sm-4">
        <input type="text" name="sid" id="id_sid" required maxlength="30" value="{{students.sid}}"/>
    </div>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Students Name: </label>
    <div class="col-sm-4">
        <input type="text" name="name" id="id_name" required maxlength="50" value="{{students.name}}"/>
    </div>
    </div>

      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Mother's Name: </label>
    <div class="col-sm-4">
        <input type="text" name="mother" id="id_mother" required maxlength="50" value="{{students.mother}}"/>
    </div>
    </div>

      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Father's Name: </label>
    <div class="col-sm-4">
        <input type="text" name="father" id="id_father" required maxlength="50" value="{{students.father}}"/>
    </div>
    </div>

   

      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Email </label>
    <div class="col-sm-4">
        <input type="text" name="email" id="id_email" required maxlength="50" value="{{students.email}}"/>
    </div>
    </div>
    
      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Degree </label>
    <div class="col-sm-4">
        <input type="text" name="degree" id="id_degree" required maxlength="40" value="{{students.degree}}"/>
    </div>
    </div>

      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Gender </label>
    <div class="col-sm-4">
        <input type="text" name="gender" id="id_gender" required maxlength="10" value="{{students.gender}}"/>
    </div>
    </div>

     <div class="form-group row">
    
    <div class="col-sm-4">
        <button type="submit" class="btn btn-success">Update</button>
    </div>
    </div>
    </div>
    </form>
    </body>
    </html>

Task1_django/djangoproject/web/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link re"stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/stu">
    {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
    </div>
    
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Students ID: </label>
    <div class="col-sm-4">
        {{form.sid}}
    </div>
    </div>

      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Students Name: </label>
    <div class="col-sm-4">
        {{form.name}}
    </div>
    </div>

      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Mother's Name: </label>
    <div class="col-sm-4">
        {{form.mother}}
    </div>
    </div>
      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Father's Name: </label>
    <div class="col-sm-4">
        {{form.father}}
    </div>
    </div>
      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Email: </label>
    <div class="col-sm-4">
        {{form.email}}
    </div>
    </div>
      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Degree: </label>
    <div class="col-sm-4">
        {{form.degree}}
    </div>
    </div>

      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Gender: </label>
    <div class="col-sm-4">
        {{form.gender}}
    </div>
    </div>

      <div class="form-group row">
    <div class="col-sm-4">
        <button type="submit">submit</button>
    </div>
    </div>

    </div>
    </form>
    </body>

Task1_django/djangoproject/web/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Students Record</title>
    {% load static %}
    <linl rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Students ID</th>
        <th>Students Name</th>
        <th>Mother's Name</th>
        <th>Father's Name</th>
        <th>Email</th>
        <th>Degree</th>
        <th>Gender</th>
        <th>Actions</th>
    </tr>
    </thead>
    </tbody>
{% for studentshow in studentvar %}
    <tr>
        <td>{{studentshow.sid}}</td>
        <td>{{studentshow.name}}</td>
        <td>{{studentshow.father}}</td>
        <td>{{studentshow.mother}}</td>
        <td>{{studentshow.email}}</td>
        <td>{{studentshow.degree}}</td>
        <td>{{studentshow.gender}}</td>
        <td>
            <a href="/edit/{{studentshow.id}}"<span class="glyphicon glyphicon-pencil">Edit</span></a>
            <a href="/delete/{{studentshow.id}}">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
<br>
<center><a href="/stu" class=">btn btn-primary">Add New Record</a></center>
</body>